# Generated by Django 4.2.7 on 2026-06-12 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_size', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('completed', 'Completed'), ('disbanded', 'Disbanded')], default='forming', max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('domain_focus', models.CharField(blank=True, choices=[('ai', 'Artificial Intelligence'), ('web', 'Web Development'), ('mobile', 'Mobile Apps'), ('cybersecurity', 'Cybersecurity'), ('healthtech', 'HealthTech'), ('agritech', 'AgriTech'), ('fintech', 'FinTech'), ('edtech', 'EdTech'), ('iot', 'IoT'), ('blockchain', 'Blockchain'), ('data', 'Data Science'), ('gaming', 'Gaming'), ('ar_vr', 'AR/VR'), ('sustainability', 'Sustainability'), ('social', 'Social Impact'), ('other', 'Other')], max_length=50)),
                ('looking_for_roles', models.CharField(blank=True, help_text='Comma-separated roles needed', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_team', models.CharField(blank=True, choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('ml', 'AI/ML Engineer'), ('uiux', 'UI/UX Designer'), ('mobile', 'Mobile Developer'), ('blockchain', 'Blockchain Developer'), ('devops', 'DevOps Engineer'), ('cybersecurity', 'Cybersecurity Expert'), ('data', 'Data Analyst'), ('presenter', 'Presenter / Business Analyst'), ('other', 'Other')], max_length=50)),
                ('team_role', models.CharField(choices=[('leader', 'Team Leader'), ('member', 'Member'), ('mentor', 'Mentor')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='profiles.studentprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'recipient')},
            },
        ),
    ]
