# Generated by Django 4.2.7 on 2026-06-12 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='globe', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(blank=True, default='code', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year / PG')], default='1', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('resume_link', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('preferred_role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('ml', 'AI/ML Engineer'), ('uiux', 'UI/UX Designer'), ('mobile', 'Mobile Developer'), ('blockchain', 'Blockchain Developer'), ('devops', 'DevOps Engineer'), ('cybersecurity', 'Cybersecurity Expert'), ('data', 'Data Analyst'), ('presenter', 'Presenter / Business Analyst'), ('other', 'Other')], default='backend', max_length=50)),
                ('availability', models.CharField(choices=[('available', 'Available for Teams'), ('busy', 'Currently Busy'), ('open', 'Open to Opportunities'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('preferred_team_size', models.IntegerField(default=4)),
                ('achievements', models.TextField(blank=True)),
                ('languages_known', models.CharField(blank=True, help_text='Comma-separated list', max_length=300)),
                ('hackathons_participated', models.IntegerField(default=0)),
                ('teams_participated', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('shortlisted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('years_experience', models.FloatField(default=0.5)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.interestdomain')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'domain')},
            },
        ),
    ]
