# Generated by Django 4.2.7 on 2026-06-12 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('organizer', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domain', models.CharField(blank=True, choices=[('ai', 'Artificial Intelligence'), ('web', 'Web Development'), ('mobile', 'Mobile Apps'), ('cybersecurity', 'Cybersecurity'), ('healthtech', 'HealthTech'), ('agritech', 'AgriTech'), ('fintech', 'FinTech'), ('edtech', 'EdTech'), ('iot', 'IoT'), ('blockchain', 'Blockchain'), ('data', 'Data Science'), ('gaming', 'Gaming'), ('ar_vr', 'AR/VR'), ('sustainability', 'Sustainability'), ('social', 'Social Impact'), ('other', 'Other')], max_length=50)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('ended', 'Ended')], default='upcoming', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('min_team_size', models.IntegerField(default=2)),
                ('max_team_size', models.IntegerField(default=5)),
                ('eligibility', models.CharField(blank=True, max_length=300)),
                ('prize_pool', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hackathons/')),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration_deadline'],
            },
        ),
        migrations.CreateModel(
            name='HackathonBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='hackathons.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hackathon')},
            },
        ),
        migrations.CreateModel(
            name='HackathonApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('winner', 'Winner'), ('participant', 'Participant')], default='applied', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hackathons.hackathon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teams.team')),
            ],
            options={
                'unique_together': {('hackathon', 'team')},
            },
        ),
    ]
