# Generated by Django 4.2.7 on 2026-06-12 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('domain_score', models.FloatField(default=0)),
                ('role_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('availability_score', models.FloatField(default=0)),
                ('match_reason', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_a', to='profiles.studentprofile')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_b', to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student_a', 'student_b')},
            },
        ),
    ]
